# Build a lightweight Python image
FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy installed packages from builder
COPY --from=builder /root/.local /root/.local

COPY ../src ./src
COPY ../config ./config

# Set environment variables for Python
ENV PYTHONUNBUFFERED=1
ENV PATH=/root/.local/bin:$PATH

CMD ["python", "src/main.py"]
